features:
  logo: 1
  name: 1
  slogan: 1
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 0
  path: 'public://favicon_0.png'
  mimetype: image/png
