# Schema for the configuration files of the Devel module.

devel.settings:
  type: mapping
  label: 'Devel settings'
  mapping:
    query_display:
      type: boolean
      label: 'Query display'
    query_sort:
      type: integer
      label: 'Query sort'
    execution:
      type: integer
      label: 'Execution thresold'
    api_url:
      type: string
      label: 'Drupal.org api url'
    timer:
      type: integer
      label: 'Timer'
    memory:
      type: integer
      label: 'Memory'
    redirect_page:
      type: integer
      label: 'Redirect page'
    page_alter:
      type: boolean
      label: 'Page alter'
    raw_names:
      type: boolean
      label: 'Raw names'
    error_handlers:
      label: 'Error handlers'
      type: mapping
      mapping:
        error_handler_type:
          type: 'integer'
          label: 'Error handler type'
        error_handler_value:
          type: 'integer'
          label: 'Error handler value'
    krumo_skin:
      type: string
      label: 'Krumo skin'
    rebuild_theme:
      type: boolean
      label: 'Rebuild theme information'
    debug_mail_file_format:
      type: string
      label: 'Mail debug file format'
    debug_mail_directory:
      type: string
      label: 'Mail debug directory'
