custom:
  -
    path: /
    priority: '1.0'
  -
    path: /places
    priority: '1.0'
entity_types:
  node_type:
    place:
      index: 1
      priority: '0.5'
    page:
      index: 1
      priority: '0.5'
settings:
  max_links: 2000
  cron_generate: true
  remove_duplicates: true
  batch_process_limit: 1500
_core:
  default_config_hash: fICH612phS7-D_8q-m1YjgYFM8Mcy_5JestT1H_nkPQ
